// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nidhi.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nidhi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NidhiDbContext))]
    [Migration("20260924103810_InitialDataFoundation")]
    partial class InitialDataFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_role");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("EventId")
                        .HasName("PK_audit_events");

                    b.HasIndex("TimestampUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_audit_events_timestamp");

                    b.HasIndex("Action", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_audit_events_action");

                    b.HasIndex("ActorId", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_audit_events_actor");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.CustomerProfile", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CustomerId")
                        .HasName("PK_customer_profiles");

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountLkr")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_lkr");

                    b.Property<decimal?>("AppliedPricePerGramLkr")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("applied_price_per_gram_lkr");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("GoldQuantityGrams")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("gold_quantity_grams");

                    b.Property<Guid>("IdempotencyRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_record_id");

                    b.Property<decimal?>("PostOperationGoldHoldingGrams")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("post_gold_holding_grams");

                    b.Property<decimal>("PostOperationWalletBalanceLkr")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("post_wallet_balance_lkr");

                    b.Property<Guid?>("PriceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("TransactionId")
                        .HasName("PK_financial_transactions");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_financial_transactions_created_at");

                    b.HasIndex("IdempotencyRecordId")
                        .IsUnique()
                        .HasDatabaseName("UK_financial_transactions_idempotency");

                    b.HasIndex("PriceVersionId");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_financial_transactions_customer_created");

                    b.ToTable("financial_transactions", null, t =>
                        {
                            t.HasCheckConstraint("chk_transactions_amount_range", "amount_lkr >= 100 AND amount_lkr <= 1000000");

                            t.HasCheckConstraint("chk_transactions_gold_purchase_fields", "(type = 'WALLET_FUNDING' AND gold_quantity_grams IS NULL AND price_version_id IS NULL AND applied_price_per_gram_lkr IS NULL AND post_gold_holding_grams IS NULL) OR (type = 'GOLD_PURCHASE' AND gold_quantity_grams IS NOT NULL AND gold_quantity_grams > 0 AND price_version_id IS NOT NULL AND applied_price_per_gram_lkr IS NOT NULL AND applied_price_per_gram_lkr > 0 AND post_gold_holding_grams IS NOT NULL AND post_gold_holding_grams >= gold_quantity_grams)");

                            t.HasCheckConstraint("chk_transactions_status_valid", "status = 'COMPLETED'");

                            t.HasCheckConstraint("chk_transactions_type_valid", "type IN ('WALLET_FUNDING', 'GOLD_PURCHASE')");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.GoldHolding", b =>
                {
                    b.Property<Guid>("HoldingId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("QuantityGrams")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity_grams");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("HoldingId")
                        .HasName("PK_gold_holdings");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UK_gold_holdings_customer_id");

                    b.ToTable("gold_holdings", null, t =>
                        {
                            t.HasCheckConstraint("chk_gold_holdings_quantity_non_negative", "quantity_grams >= 0");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.GoldPrice", b =>
                {
                    b.Property<Guid>("PriceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<decimal>("PricePerGramLkr")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_per_gram_lkr");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("PublishedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_admin_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("PriceVersionId")
                        .HasName("PK_gold_prices");

                    b.HasIndex("PublishedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_gold_prices_published_at_utc");

                    b.HasIndex("PublishedByAdminId");

                    b.ToTable("gold_prices", null, t =>
                        {
                            t.HasCheckConstraint("chk_gold_prices_price_positive", "price_per_gram_lkr > 0");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdempotencyRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResponseTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("IdempotencyRecordId")
                        .HasName("PK_idempotency_records");

                    b.HasIndex("ResponseTransactionId")
                        .HasDatabaseName("IX_idempotency_response_tx");

                    b.HasIndex("CustomerId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UK_idempotency_scoped_key");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("chk_idempotency_status_valid", "status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.LedgerAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_number");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.HasKey("AccountId")
                        .HasName("PK_ledger_accounts");

                    b.HasAlternateKey("AccountId", "Unit")
                        .HasName("AK_ledger_accounts_id_unit");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("UK_ledger_accounts_account_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_ledger_accounts_customer_id");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_ledger_accounts_class_valid", "classification IN ('ASSET', 'LIABILITY', 'EQUITY', 'CLEARING')");

                            t.HasCheckConstraint("chk_ledger_accounts_unit_valid", "unit IN ('LKR', 'GOLD_GRAMS')");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.HasKey("EntryId")
                        .HasName("PK_ledger_entries");

                    b.HasIndex("AccountId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ledger_entries_account_created");

                    b.HasIndex("AccountId", "Unit");

                    b.HasIndex("TransactionId", "Unit")
                        .HasDatabaseName("IX_ledger_entries_tx_unit");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("chk_ledger_entries_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_ledger_entries_direction_valid", "direction IN ('DEBIT', 'CREDIT')");

                            t.HasCheckConstraint("chk_ledger_entries_unit_valid", "unit IN ('LKR', 'GOLD_GRAMS')");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.SavingsGoal", b =>
                {
                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TargetDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date_utc");

                    b.Property<decimal>("TargetGrams")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("target_grams");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("GoalId")
                        .HasName("PK_savings_goals");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_savings_goals_customer_id");

                    b.HasIndex(new[] { "CustomerId" }, "ActiveGoal")
                        .IsUnique()
                        .HasDatabaseName("uq_savings_goals_one_active_per_customer")
                        .HasFilter("status = 'ACTIVE'");

                    b.ToTable("savings_goals", null, t =>
                        {
                            t.HasCheckConstraint("chk_savings_goals_status_valid", "status IN ('ACTIVE', 'COMPLETED', 'REPLACED')");

                            t.HasCheckConstraint("chk_savings_goals_target_positive", "target_grams > 0");
                        });
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BalanceLkr")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance_lkr");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("WalletId")
                        .HasName("PK_wallets");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UK_wallets_customer_id");

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("chk_wallets_balance_max_cap", "balance_lkr <= 5000000");

                            t.HasCheckConstraint("chk_wallets_balance_non_negative", "balance_lkr >= 0");
                        });
                });

            modelBuilder.Entity("Nidhi.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nidhi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nidhi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nidhi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nidhi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.CustomerProfile", b =>
                {
                    b.HasOne("Nidhi.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Nidhi.Domain.Entities.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nidhi.Domain.Entities.IdempotencyRecord", null)
                        .WithOne()
                        .HasForeignKey("Nidhi.Domain.Entities.FinancialTransaction", "IdempotencyRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nidhi.Domain.Entities.GoldPrice", null)
                        .WithMany()
                        .HasForeignKey("PriceVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.GoldHolding", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.CustomerProfile", null)
                        .WithOne()
                        .HasForeignKey("Nidhi.Domain.Entities.GoldHolding", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.GoldPrice", b =>
                {
                    b.HasOne("Nidhi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PublishedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nidhi.Domain.Entities.FinancialTransaction", null)
                        .WithMany()
                        .HasForeignKey("ResponseTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.LedgerAccount", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.FinancialTransaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nidhi.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "Unit")
                        .HasPrincipalKey("AccountId", "Unit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.SavingsGoal", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nidhi.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Nidhi.Domain.Entities.CustomerProfile", null)
                        .WithOne()
                        .HasForeignKey("Nidhi.Domain.Entities.Wallet", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
